[global]
# Number of seconds to wait before checking the signatures again for each chain
rest_period = 15

# Number of past blocks to check for signatures if the network has never been scanned before
initial_scan = 200

# DB file location
db_location = "./cometbft_signatures.db"

# Port to listen for incoming requests
http_port = 8080


[[chains]]
# Chain ID of the CometBFT network
chain_id = "juno-1"

# RPC endpoint of the chain
host = "http://127.0.0.1:26657"

# HEX pubkey of the validator signing key
address = "A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1"

# delay between RPC calls in case the node cant handle the load - Default: "0ms"
rpc_delay = "100ms"

# signing window for the validator (number of blocks to check for signatures)
signing_window = 5000

# Enable pruning (pruning removes all records older than signing_window) Default: true
pruning = true


[[chains]]
chain_id = "osmosis-1"
host = "http://127.0.0.1:36657"
address = "A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1A1"
rpc_delay = "100ms"
signing_window = 30000
pruning = true